from . import foto
from . import coordenada
from . import balance_energetico
from . import canton
from . import consumidor
from . import marca_medidor
from . import provincia
from . import potencia
from . import punto_carga
from . import red
from . import tipo_consumidor
from . import tipo_vinculacion
from . import transformador
from . import vinculacion